### ISSUE TITLE
Helper bot

### ISSUE THREAD

**Issue by chirgwin** [jbaudanza/subnetchat#1]
Bot to offer help, maybe to new users if no other users connected

**Comment by jbaudanza** [comment]
Took a stab at drafting some txt for this:

Welcome to subnetchat.com! This chat room is only accessible to people on your local subnet. Your subnet refers to the network of computers that are directly connected to you. This could be your office, school, or neighborhood block. Your IP address is **173.247.204.59**, so messages in this chat room will only be visible to people with an IP address that starts with **173.247.204.***

**Comment by jbaudanza** [comment]
Done in 8bf573f
