### ISSUE TITLE
improve avatar icons

### ISSUE THREAD

**Issue by chirgwin** [jbaudanza/subnetchat#2]
![screen shot 2016-10-24 at 3 35 55 pm](https://cloud.githubusercontent.com/assets/165955/19666498/a500d314-99ff-11e6-8509-eb78f831a28f.png)

**Comment by jbaudanza** [comment]
I think this should be good enough for now:

<img width="455" alt="screen shot 2016-12-13 at 1 31 40 pm" src="https://cloud.githubusercontent.com/assets/35914/21160109/879ce262-c138-11e6-89a2-1c825ceb35c0.png">
